Workflow: Enable nightly deployment of Docker container
fjtrujy/psp-pkgconf pull request #2
Opened 2023-04-24 00:13 UTC by MotoLegacy

Previously, the `psp-pkgconf` Docker container was only set to be updated whenever a commit was made. The latest commit being from October 2021, means that packages are considerably out of date. This currently impacts `psp-pacman`, which, due to being built with an old OpenSSL version (`v1.1.1`, from Alpine `v3.14`), does not run on the main `pspdev` Docker image.

2023-04-25 08:14 UTC, sharkwouter approved these changes

2023-04-25 08:15 UTC, sharkwouter commented
Wait, do we actually use this repo at all?

2023-04-25 08:18 UTC, sharkwouter commented
Actually, close this. We just install a shell script and do not use this repo: https://github.com/pspdev/psptoolchain-extra/blob/main/scripts/002-psp-pkg-config.sh

2023-04-25 08:18 UTC, sharkwouter requested changes
Please close this

2023-04-25 15:20 UTC, MotoLegacy commented
> Wait, do we actually use this repo at all?

Yes we do. It is the cause for pacman requesting openssl 1.1 in the pspdev docker.

https://github.com/pspdev/psp-pacman/blob/21c98d6d1268196084c0532127d04fcc28e25c5c/.github/workflows/compilation.yml#L12

2023-04-26 07:21 UTC, sharkwouter commented
Oh that's bad. That should be changed.

2023-05-31 15:45 UTC, closed without merging